[package]
name = "coppernotes"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
rusqlite = "0.25.3"
chrono = "0.4.19"
log = "0.4"